shell = { program = "bash" }

import = [
  # "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "Fira Code", style = "Regular" }
size = 15

[colors.primary]
background = '#000000'
foreground = '#e8e8e8'

[cursor]
style = 'Block'
